SmaPetz/SmaPetz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SmaPetz/cart/urls.py
from django.urls import path
from .views import cart_detail, success

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart'),
    path('success/', success, name='success')
]

SmaPetz/posts/urls.py
from django.urls import path
from .views import home_view, PostDeleteView, PostUpdateView, like_unlike_post

app_name = 'posts'

urlpatterns = [
    path('', home_view, name='home-view'),
    path('liked/',like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

SmaPetz/profiles/urls.py
from django.urls import path
from .views import (
    profile_test_view,
    received_requests_view,
    profiles_list_view, 
    invite_profiles_list_view, 
    ProfileListView,
    ProfileDetailView, 
    send_requests, 
    remove_from_friends,
    accept_requests,
    reject_requests,
    add_products,
    display_orders
)

app_name = 'profiles'

urlpatterns = [
    # path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('profile/', profile_test_view, name='profile-test'),
    path('received-requests/', received_requests_view, name='received-requests'),
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('add_products/', add_products, name='add-products'),
    path('display_orders/', display_orders, name='display-orders'),
    
    path('<slug:slug>', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('to-request/', invite_profiles_list_view, name='request-profiles-view'),
    path('send-requests/',send_requests, name='send-request'),
    path('remove-friend/',remove_from_friends, name='remove-friend'),
    path('received-requests/accept/', accept_requests, name='accept-request'),
    path('received-requests/reject/', reject_requests, name='reject-request'),  
    
]

SmaPetz/posts/models.py
from django.db import models
from django.db import models
from profiles.models import Profile
from .validators import fileSize
from django.core.validators import FileExtensionValidator

#Post Model
class Post(models.Model):
    picture = models.ImageField(upload_to='images/', null=True , blank= True)
    video =  models.FileField(upload_to='videos/', blank= True, validators=[fileSize, FileExtensionValidator(['mp4'])])
    caption = models.TextField()
    liked_by = models.ManyToManyField(Profile, default=None, blank=True, related_name='likes')
    tags = models.CharField(max_length=100, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE,related_name='posts')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author}-{self.caption}"
    
#to grab the number of likes
    def num_likes(self):
        return self.liked_by.all().count()

#to grab the number of comments
    def num_comments(self):
        return self.comment_set.all().count()


#to create the ordering of the posts by time
    class Meta:
        ordering = ('-created',)


#Comment Model 
class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

#Reaction Model
LIKE_CHOICES = (
    
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

SmaPetz/posts/forms.py
from django import forms
from django.forms import fields
from .models import Post, Comment

class postModelForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ('caption', 'picture', 'video', 'tags')
    widgets = {
      'caption': forms.Textarea(attrs={'rows':3,'cols':50, 'class':'form-control'}),
      'tags': forms.Textarea(attrs={'rows':1, 'cols':50, 'class':'form-control'}),
    }

class commentModelForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder':'Add a comment...', 'class':'form-control'}))
    class Meta:
          model = Comment
          fields = ('body',)

SmaPetz/posts/views.py
from django.contrib import messages
import django
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Post, Like
from profiles.models import Pet, Profile, Veterinarian, Store, Pet_Lover
from django.shortcuts import render
from .forms  import commentModelForm, postModelForm
from django.http import HttpResponseRedirect
from django.views.generic import UpdateView, DeleteView
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import random


# Create your views here.
@login_required
def home_view(request):
    #query set to grab all the posts
    post =  Post.objects.all()
    profile = Profile.objects.get(user=request.user)    
    written = Post.objects.exclude(picture="")
    video = Post.objects.exclude(video="")

    pros = Profile.objects.all().exclude(user=request.user)
    show_pros = random.sample(list(pros), 4)

    #Post and Comment Forms
    post_form = postModelForm()
    comment_form = commentModelForm()
    post_added = False

    if 'post_form_submit' in request.POST:
        print(request.POST)
        post_form = postModelForm(request.POST, request.FILES)
        if post_form.is_valid():
            instance = post_form.save(commit=False)
            instance.author = profile
            instance.save()
            post_form = postModelForm()
            post_added = True
        return redirect('posts:home-view')



    if 'comment_form_submit' in request.POST:
        comment_form = commentModelForm(request.POST)
        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            comment_form = commentModelForm()
        return redirect('posts:home-view')


    context = {
        'profile': profile,
        'post':post,
        'written':written,
        'video':video,
        'post_form':post_form,
        'comment_form':comment_form,
        'post_added': post_added,
        'show_pros' : show_pros
    }

    return render(request, 'posts/main.html', context)

@login_required
def like_unlike_post(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id = post_id)
        profile = Profile.objects.get(user = user)

        if profile in post_obj.liked_by.all():
            post_obj.liked_by.remove(profile)
        else:
            post_obj.liked_by.add(profile)

        like, created = Like.objects.get_or_create(user = profile, post_id = post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'

            post_obj.save()
            like.save()
        data ={
            'value': like.value,
            'likes': post_obj.liked_by.all().count()
        }
        return JsonResponse(data, safe= False)
        
    return redirect('posts:home-view')
        

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('posts:home-view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.request, 'You need to be the author of the post in order to delete it.')
        return obj

class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = postModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url= reverse_lazy('posts:home-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)

        else:
            form.add_error(None, "You need to be the author of the post in order to update it.")
            return super().form_invalid(form)

SmaPetz/posts/templates/posts/confirm_del.html
{% extends 'base.html' %}

{% block title %}
    Delete Post
{% endblock title %}


{% block content %}
    
    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div class="alert alert-warning" role="alert">
                    <div class="header">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}  
    {% endif %}

    
    {% if not messages %}
    <section class="vh-100 m-3">
        <div class="d-flex justify-content-center mb-5">
            <div class="col-xl-20 offset-xl-1 shadow p-3 mb-5 bg-white rounded">               
                <h3 class="modal-title">Delete Post</h3>
                <hr>
                <form action="" method="post" class ="form-group bg-white">
                    {% csrf_token %}
                    <p class="bg-white">Are you sure you want to delete the post?</p>
                    <button type="submit" class="btn btnModal">Delete</button>
                </form>   
            </div>
        </div>
    </section>
    {% endif %}
        

        
{% endblock content %}
    
    

SmaPetz/posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block scripts %}
    <link rel="stylesheet" href={% static 'posts/post.css' %}>
    <script src={% static 'posts/post.js' %} defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

{% endblock scripts %}

{% block title %}
    home
{% endblock title %}

{% block content %}

<div class="container pl-pr-2 pt-3">
    <div class="row">
        <div class="col-8">
            {% for obj in post %}
            <div class="card">
                <div class ="card-title clearfix ml-4 mt-4">
                    <img class="img-fluid avatar mr-3" alt="Responsive image" src={{obj.author.profilePic.url}}>

                    {{obj.author.user.name}} - {{obj.created|timesince}} ago
             
                    {% if request.user == obj.author.user %}
                        <a href="{% url 'posts:post-delete' obj.pk %}"><button class="btn btn-title float-right ml-3 mr-4">Delete</button></a>
                        <a href="{% url 'posts:post-update' obj.pk %}"><button class="btn btn-title float-right ml-3">Update</button></a>
                    {% endif %}
                </div>
                {% if obj in written %}
                    <img src={{obj.picture.url}} class="card-img-top" alt="...">
                {% elif obj in video %}
                    <video controls autoplay muted id="vid">
                        <source src={{obj.video.url}} type="video/mp4"></source>
                    </video>
                {% endif %}
                <div class="card-body">
                    <h6 class="card-title-caption">{{obj.caption}}</h6>
                    <p class="card-text">{{obj.tags}}</p>
                    <!-- Like -->
                    <div class="card-body-likes float-right">
                        <form action="{% url 'posts:like-post-view' %}" method="POST" class="like-form" id="{{obj.id}}">
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value={{obj.id}}>
                            <button type="submit" class="btn likeBtn like-btn{{obj.id}}">
                                {% if profile not in obj.liked_by.all %}
                                    Like
                                {% else %}
                                    Unlike
                                {% endif %}
                            </button>
                            <i class="like-count{{obj.id}}"> {{obj.num_likes}} likes </i>
                            <br>
                            <div class="grid">
                                <div class="col">
                                    
                                </div>
                            </div> 
                        </form>
                    </div>
                    <!-- Comments -->
                    <div class ="card-body-comment">
                        <div class="extra content">
                            <i class="fa-solid fa-comment ml-5"></i>
                            <span> {{ obj.num_comments}}</span>
                            <button class="btn cmtbutton mb-5" style="margin-bottom:5px !important;">show / hide comments</button>
                            <div class="comment-box" style="display: none !important;">
                                {% if obj.comment_set.all %}
                                    {% for c in obj.comment_set.all %}
                                        <div class="segment mb-5" style="margin-bottom:5px !important;">
                                            <img class="img-fluid cmtavatar p-2" src={{c.user.profilePic.url}}>
                                            <span>{{c.user}}</span>
                                            <div class='mt-2'>{{ c.body }}</div>
                                            <hr>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                        <form action="" method="POST" class="form-group">
                            {% csrf_token %}
                            {{comment_form|crispy}}
                            <input type ="hidden" name="post_id" value={{obj.id}}>
                            <button type="submit" class="btn btnModal" name="comment_form_submit">Comment</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>


        <div class="col-4">
            <!-- Button trigger Post Modal -->
            <button type="button" class="btn btn-post mt-3 ml-5" data-toggle="modal" data-target="#exampleModal">
                Add a Post
            </button>
            {% if post_added %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    Post Added
                </div>
            {% endif %}
            
            <!-- Friend Suggestions -->
            <div class="card suggestions mt-5">
                <div class="card-body">
                    {% comment %} {{request.user.type}}{% endcomment %}
                    <h6 class='sugesttitle mb-3'>Friend Suggestions</h6>
                    {% for pro in show_pros %}
                        <div class="card m-3 StoreProduct" style="width: 18rem; height: 6rem;">
                            <table class="suggestFriends">
                                <tr>
                                    <td rowspan="2" class="align-baseline"><img class="img-fluid avatar-img" alt="Responsive image" src={{pro.profilePic.url}}></td>
                                    <td class="align-baseline"><h6 class="card-title suggestName">{{pro.user.name}}</h6></td>
                                    <td rowspan="2" class="align-baseline">
                                        <a href="{% url 'profiles:profile-detail-view' pro.slug %}">
                                            {% if pro.user.type == 'PET' %}
                                                <i class="fa-solid fa-paw suggestIcon"></i>
                                            {% endif %}
                                            {% if pro.user.type == 'VET' %}
                                                <i class="fa-solid fa-user-doctor suggestIcon"></i>
                                            {% endif %}
                                            {% if pro.user.type == 'STORE' %}
                                                <i class="fa-solid fa-store suggestIcon"></i>
                                            {% endif %}
                                            {% if pro.user.type == 'PET_LOVER' %}
                                                <i class="fa-solid fa-face-kiss-wink-heart suggestIcon"></i>
                                            {% endif %}
                                        </a>
                                    </td>
                                </tr>    
                            </table>
                        </div>
                    {% endfor %}

                </div>
            </div>

            <!-- Post Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog postModal">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Create a Post</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        
                        <form action="" method="POST" class ="form-group" enctype="multipart/form-data">
                            <div class="modal-body">
                                {% csrf_token %}
                                <div class="form-outline mb-4">
                                    <label class="form-label bg-white labelUpdate" for="form3Example3">Caption :</label>
                                    <div class="form-group" id="form3Example3">
                                        {{ post_form.caption }}
                                    </div>
                                    <label class="form-label bg-white labelUpdate" for="form3Example3">Picture :</label>
                                    <div class="form-group" id="form3Example3">
                                        {{ post_form.picture }}
                                    </div>
                                    <label class="form-label bg-white labelUpdate" for="form3Example3">Video :</label>
                                    <div class="form-group" id="form3Example3">
                                        {{ post_form.video }}
                                    </div>
                                    <label class="form-label bg-white labelUpdate" for="form3Example3">Tags :</label>
                                    <div class="form-group" id="form3Example3">
                                        {{ post_form.tags }}
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btnModal" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btnModal"  name="post_form_submit">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

SmaPetz/posts/templates/posts/post_list.html
<div class="card m-3" style="width: 28rem;">
    <div class ="card-title clearfix p-2">
        <img class="img-fluid avatar mr-3" alt="Responsive image" src={{post.author.profilePic.url}}>
        {{post.author.user.name}} - {{post.created|timesince}} ago
    </div>
        {% if post.picture %}
            <img src="{{post.picture.url}}" class="img-vet" alt="...">
        {% endif %}
        {% if post.video %}
            <video controls autoplay muted id="vid">
                <source src={{post.video.url}} type="video/mp4"></source>
            </video>
        {% endif %}
    <div class="card-body">
        <h6 class="card-title">{{post.caption}}</h5>
        <p class="card-tags vetTags">{{post.tags}}</p>
    </div>
    <div class="card-footer">
        <a href="{% url 'profiles:profile-detail-view' post.author.slug %}" class="btn productView" style="color:#fff !important;">Sniff Profile</a>
    </div>
</div>

SmaPetz/posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}
update post
{% endblock title %}

{% block content %}
<section class="vh-100 m-3">
    <div class="d-flex justify-content-center mb-5">
        <div class="col-xl-20 offset-xl-1 shadow p-3 mb-5 bg-white rounded">
            <div class="modal-update">
                <h3 class="modal-title">Update Post</h3>
                <hr>
                <form action="" method="post" class ="form-group" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-outline mb-4">
                        <label class="form-label bg-white labelUpdate" for="form3Example3">Caption :</label>
                        <div class="form-group" id="form3Example3">
                            {{ form.caption }}
                        </div>
                        <label class="form-label bg-white labelUpdate" for="form3Example3">Picture :</label>
                        <div class="form-group bg-white" id="form3Example3">
                            {{ form.picture }}
                        </div>
                        <label class="form-label bg-white labelUpdate" for="form3Example3">Video :</label>
                        <div class="form-group" id="form3Example3">
                            {{ form.video }}
                        </div>
                        <label class="form-label bg-white labelUpdate" for="form3Example3">Tags :</label>
                        <div class="form-group" id="form3Example3">
                            {{ form.tags }}
                        </div>
                    </div>
                    <div class="d-flex justify-content-end bg-white pr-3">
                        <button type="submit" class="btn btnModal">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
