SmaPetz/SmaPetz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SmaPetz/cart/urls.py
from django.urls import path
from .views import cart_detail, success

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart'),
    path('success/', success, name='success')
]

SmaPetz/products/urls.py
from django.urls import path
from .views import store_view, product, category, searchProduct

app_name = 'products'

urlpatterns = [
    path('store/', store_view, name='store-view'),
    path('search/', searchProduct, name='product-search'),
    path('<slug:category_slug>/<slug:product_slug>/', product, name='product'),
    path('<slug:category_slug>/', category, name='category'),
]

SmaPetz/profiles/urls.py
from django.urls import path
from .views import (
    profile_test_view,
    received_requests_view,
    profiles_list_view, 
    invite_profiles_list_view, 
    ProfileListView,
    ProfileDetailView, 
    send_requests, 
    remove_from_friends,
    accept_requests,
    reject_requests,
    add_products,
    display_orders
)

app_name = 'profiles'

urlpatterns = [
    # path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('profile/', profile_test_view, name='profile-test'),
    path('received-requests/', received_requests_view, name='received-requests'),
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('add_products/', add_products, name='add-products'),
    path('display_orders/', display_orders, name='display-orders'),
    
    path('<slug:slug>', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('to-request/', invite_profiles_list_view, name='request-profiles-view'),
    path('send-requests/',send_requests, name='send-request'),
    path('remove-friend/',remove_from_friends, name='remove-friend'),
    path('received-requests/accept/', accept_requests, name='accept-request'),
    path('received-requests/reject/', reject_requests, name='reject-request'),  
    
]

SmaPetz/users/urls.py
from django.urls import path, re_path, reverse_lazy
from .views import register, login_view, logout_view, home_view, about_view,vet_view, searchVet
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'users'

urlpatterns = [
    path('', home_view, name='dashboard'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('about/', about_view, name='about-view'),    
    path('vet/', vet_view, name='vet-view'), 
    path('vetSearch/', searchVet, name='search-vet'),
]

SmaPetz/posts/models.py
from django.db import models
from django.db import models
from profiles.models import Profile
from .validators import fileSize
from django.core.validators import FileExtensionValidator

#Post Model
class Post(models.Model):
    picture = models.ImageField(upload_to='images/', null=True , blank= True)
    video =  models.FileField(upload_to='videos/', blank= True, validators=[fileSize, FileExtensionValidator(['mp4'])])
    caption = models.TextField()
    liked_by = models.ManyToManyField(Profile, default=None, blank=True, related_name='likes')
    tags = models.CharField(max_length=100, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE,related_name='posts')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author}-{self.caption}"
    
#to grab the number of likes
    def num_likes(self):
        return self.liked_by.all().count()

#to grab the number of comments
    def num_comments(self):
        return self.comment_set.all().count()


#to create the ordering of the posts by time
    class Meta:
        ordering = ('-created',)


#Comment Model 
class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

#Reaction Model
LIKE_CHOICES = (
    
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

SmaPetz/users/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

# Create custom model manager

class MyUserManager(BaseUserManager):
    def create_user(self, email, type, name, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            type=type,
            name = name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, type, name, password=None):
        user = self.create_user(
            email,
            password=password,
            type=type,
            name = name,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user

#create custom user model

class User(AbstractBaseUser):
    class Types(models.TextChoices):
        PET = "PET", "Pet"
        VET = "VET", "Veterinarian"
        STORE = "STORE", "Store"
        PET_LOVER = "PET_LOVER", "Pet lover"

    email = models.EmailField(max_length=255,unique=True)
    type = models.CharField(max_length=50, choices=Types.choices, default=Types.PET_LOVER)
    name = models.CharField(blank=True, max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'type']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"

        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        
        return self.is_admin

    

SmaPetz/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from users.models import User

class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'type', 'password1', 'password2')
        widgets = {
            'email': forms.EmailInput(attrs={'class':'form-control custom-class'}),
            'name': forms.TextInput(attrs={'class':'form-control custom-class'}),
       }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['type'].widget.attrs.update({'class':'form-control custom-class'})
        self.fields['password1'].widget.attrs.update({'class':'form-control custom-class'})
        self.fields['password2'].widget.attrs.update({'class':'form-control custom-class'})

class UserLoginForm(forms.ModelForm):
    password = forms.CharField(label="password", widget=forms.PasswordInput(attrs={'class':'form-control custom-class'}))

    class Meta:
        model = User
        fields = ('email', 'password')
        widgets = {
            'email': forms.EmailInput(attrs={'class':'form-control custom-class'}),
        }

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']

            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Invalid Credentials")


SmaPetz/users/views.py
from cProfile import Profile
import profile
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from profiles.models import Veterinarian
from users.forms import UserRegistrationForm, UserLoginForm
from users.models import User
from products.models import Product
from posts.models import Post
import random
from django.db.models import Q


# Create your views here.
def home_view(request):
    return redirect('posts:home-view')

def vet_view(request):
    posts = Post.objects.all()
    vets = Veterinarian.objects.all()
    
    context = {
         'posts': posts,
         'vets':vets
    }
    return render(request, 'users/vet.html', context)

def searchVet(request):
    query = request.GET.get('query', '')
    posts = Post.objects.filter(Q(caption__icontains=query) | Q(tags__icontains=query))
    profiles = Veterinarian.objects.filter(Q(address__icontains=query) | Q(bio__icontains=query) | Q(slug__icontains=query))

    
    context = {
        'query':query,
        'posts':posts,
        'profiles':profiles, 
    }
    return render(request, 'users/vet_search.html', context)

def about_view(request):
    products = list(Product.objects.all())
    show_Products = random.sample(products, 8)
    posts = list(Post.objects.exclude(picture=""))
    show_posts = random.sample(posts, 6)
    
    context = {
        'show_Products': show_Products,
        'show_posts': show_posts,
    }
    return render(request, 'users/about.html', context)

def register(request):
    context = {}
    if request.POST:
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
        context['register_form'] = form
    
    else:
        form = UserRegistrationForm()
        context['register_form'] = form
    
    return render(request, 'users/register.html', context)


def login_view(request):
    context = {}
    if request.POST:
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']

            user = authenticate(request, email=email, password = password)

            if user is not None:
                login(request, user)
                return redirect("users:dashboard")

        else:
            context['login_form'] = form

    else:
        form = UserLoginForm()
        context["login_form"] = form

    return render(request, 'users/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('users:login')

SmaPetz/users/templates/users/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
About
{% endblock title %}

{% block content %}
<div class="container aboutcon">
  <div class="row">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static "images/slide1.jpg" %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="caption carouselTitle">A Pet-Centric Social Media Experience🐾</h5>
            <p class="captionPara">What would your pet say if they could speak?</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static "images/slide2.jpg" %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="caption carouselTitle">Caring For Those Who Care For You🩺</h5>
            <p class="captionPara">Receieve veterinary advices and pet healthcare tips from experts!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static "images/slide3.jpg" %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="caption carouselTitle">Find Your New Best Friend🐱</h5>
            <p class="captionPara">Join the community and help pets to find new homes!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="{% static "images/slide4.jpg" %}" class="d-block w-100" alt="...">
          <div class="carousel-caption d-none d-md-block">
            <h5 class="caption carouselTitle">Spoil Your Pets With What They Deserve👑</h5>
            <p class="captionPara">Buy and sell pets and pet products!</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev controlsIn" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon crlIcon" aria-hidden="true">
          <i class="fa-solid fa-angle-left iconabout"></i>
        </span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next controlsIn" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon crlIcon" aria-hidden="true">
          <i class="fa-solid fa-angle-right iconabout"></i>
        </span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class="row"><h3 class='deatilTitle pl-5 pt-5'>Pet Social Media</h1><hr></div>
  <div class="row">
    {% for post in show_posts %}
      <div class="card m-3 AboutPost" style="width: 22rem; height:32rem;">
        <img src="{{post.picture.url}}" class="card-img-top postImg" alt="...">
        <div class="card-body aboutBody">
          <h6 class="card-cap">{{post.caption}}</h6>
        </div>
        <div class="card-footer">
          <a href="{% url 'profiles:profile-detail-view' post.author.slug %}" class="btn btn-block productView" style="color:#fff !important;">View Profile</a>
        </div>
      </div>
    {% endfor %}
  </div>
  <div class="row"><h3 class='deatilTitle pl-5 pt-5'>Pet Store</h1><hr></div>
  <div class="row">
      {% for product in show_Products %}
        <div class="card m-3 StoreProduct" style="width: 16rem;">
          <img src="{{product.get_thumbnail}}" class="card-img-top productImg" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{product.title}}</h5>
            <p class="card-tags">${{product.price}}</p>
          </div>
          <div class="card-footer">
            <a href="{% url 'products:product' product.category.slug product.slug %}" class="btn productView" style="color:#fff !important;">View Product</a>
          </div>
        </div>
      {% endfor %}
  </div>
</div>

{% endblock content %}


SmaPetz/users/templates/users/dashboard.html
{% extends 'base.html' %}
{% block title %}
Dash
{% endblock title %}

{% block content %}
    <h1>Dashboard</h1>
    {{request.user.name}}
    <p> <a href= "{% url 'logout' %}"> Logout</a> </p>
{% endblock content %}


SmaPetz/users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
User Login
{% endblock title %}

{% block content %}
<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-md-9 col-lg-6 col-xl-5 p-3 mb-5 rounded">
            <img src="{% static 'images/bg.png' %}" class="img-fluid" alt="Sample image">
          </div>
          <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1 shadow p-3 mb-5 bg-white rounded">
            <form action="" method="POST" class="loginForm">
                {% csrf_token %}
                <div class="form-outline mb-4">
                    <label class="form-label bg-white" for="form3Example3">Email Address</label>
                    <div class="form-group" id="form3Example3">
                        {{ login_form.email }}
                    </div>
                    <div class="form-outline mb-3">
                        <label class="form-label bg-white" for="form3Example4">Password</label>
                        <div class="form-group">
                            {{ login_form.password}}
                        </div>
                    </div>
                    <div class="form-outline mb-3">
                        {% if login_form.non_field_errors %}
                            {% for err in login_form.non_field_errors %}
                                <div class="alert alert-danger" role="alert">
                                    <small class="errorMsg">{{err}}</small>
                                    <button type="button" class="close closeError" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span> 
                                    </button>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="form-outline mt-4 mb-3">
                        <button type="submit" class="btn btn-lg btn-block loginBtn">Login</button>
                    </div>
                </div>
            </form>
            <div class="divider d-flex align-items-center bg-white my-4">
                <p class="text-center fw-bold mx-3 mb-0">Or</p>
            </div>
            <div class="text-center text-lg-start mt-4 pt-2 bg-white">
                <h6 class="fw-bold mt-2 pt-1 mb-0 bg-white">New to SmaPetz? &nbsp
                    <i class="fa-solid fa-hand-point-right bg-white"></i> &nbsp
                    <a href="{% url 'users:register' %}" style="color: #DE6262 !important;" class="bg-white">Join the Community</a> 
                </h6>
            </div>
          </div>
        </div>
    </div>
</section>
  {% endblock content %}

SmaPetz/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Password Reset
{% endblock title %}

{% block content %}
<h1>Password set</h1>
<p>
    Your password has been set. You can 
    {% comment %} <a href="{% url "users:login" %}">log in now</a> {% endcomment %}
</p>
{% endblock content %}

SmaPetz/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Password Reset
{% endblock title %}

{% block content %}
<h1>Reset your password</h1>
{% if validlink %}
    <p>Please enter your new password twice:</p>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Change my password" /></p>
    </form>
{% else %}
    <p>The password reset link was invalid, possibly because it hasalready been used. 
        Please request a new password reset.</p>
{% endif %}
{% endblock content %}

SmaPetz/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Password Reset
{% endblock title %}

{% block content %}
<h1>Reset yourpassword</h1>
<p>We've emailed you instructions for setting your password.</p>
<p>If you don't receive an email, please make sure you've entered theaddress you registered with.</p>

{% endblock content %}

SmaPetz/users/templates/users/password_reset_email.html
Someone asked for password reset for email {{ email }}. 
Follow the linkbelow:
{% comment %} {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %} {% endcomment %}

SmaPetz/users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Password Reset
{% endblock title %}

{% block content %}
<h1>Forgotten your password?</h1>
<p>Enter your e-mail address to obtain a new password.</p>
<form action="." method="post">
    {{ form.as_p }}
    <p><input type="submit" value="Send e-mail"></p>
    {% csrf_token %}
</form>

{% endblock content %}

SmaPetz/users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
User Registration
{% endblock title %}

{% block content %}
<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
          
          <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1 shadow p-3 mb-5 bg-white rounded">
            <form action="" method="POST" class="registerForm">
                {% csrf_token %}
                <div class="form-outline mb-4">
                    <label class="form-label regiLabel" for="form3Example3">Email Address</label>
                    <div class="form-group" id="form3Example3">
                        {{ register_form.email }}
                    </div>
                    <div class="form-outline mb-3">
                        <label class="form-label regiLabel" for="form3Example4">Name</label>
                        <div class="form-group">
                            {{ register_form.name }}
                        </div>
                    </div>
                    <div class="form-outline mb-3">
                        <label class="form-label regiLabel" for="form3Example4">Type</label>
                        <div class="form-group bg-white">
                            {{ register_form.type }}
                        </div>
                    </div>
                    <div class="form-outline mb-3">
                        <label class="form-label regiLabel" for="form3Example4">Password</label>
                        <div class="form-group">
                            {{ register_form.password1}}
                        </div>
                    </div>
                    <div class="form-outline mb-3">
                        <label class="form-label regiLabel" for="form3Example4">Confirm Password</label>
                        <div class="form-group">
                            {{ register_form.password2 }}
                        </div>
                    </div>
                    <div class="form-outline mb-3">
                        {% for error in register_form.errors %}
                                <div class="alert alert-danger" role="alert">
                                    <small class="errorMsg">{{error}}</small>
                                    <button type="button" class="close closeError" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                        {% endfor %}
                       
                    </div>
                    <div class="form-outline mt-4 mb-3">
                        <button type="submit" class="btn btn-lg btn-block loginBtn">Join SmaPetz</button>
                    </div>
                </div>
            </form>
            <div class="text-center text-lg-start mt-4 pt-2 bg-white">
                <h6 class="fw-bold mt-2 pt-1 mb-0 bg-white">Already a Member? &nbsp
                    <i class="fa-solid fa-hand-point-right bg-white"></i> &nbsp
                    <a href="{% url 'users:login' %}" style="color: #DE6262 !important;" class="bg-white">Login</a> 
                </h6>
            </div>
          </div>
          <div class="col-md-9 col-lg-6 col-xl-5 p-3 mb-5 rounded">
            <img src="{% static 'images/bg.png' %}" class="img-fluid" alt="Sample image">
          </div>
        </div>
    </div>
</section>
{% endblock content %}

SmaPetz/users/templates/users/vet.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Veterinarian
{% endblock title %}

{% block content %}
<div class="section pl-5">
    <div class="row mb-3">
        <div class="col-2 d-flex justify-content-end imgCol">
          <img class="img-fluid justify-content-right ml-5" alt="Responsive image" src="{% static "images/vet_clinic.png" %}">
        </div>
        <div class="col-5 d-flex align-items-start">
          <h2 class="storeHeader justify-content-left">Veterinarians</h2>
        </div>
        <div class="col">
          <form method="get" action="{% url 'users:search-vet' %}" class="formSearch">
            <div class="boxContainer">
              <table class="elementsContainer">
                <tr>
                  <td class="align-baseline"><input type ="search" class="form-control searchInput" placeholder="Search..." name="query"></td>
                  <td rowspan="2" class="align-baseline"><button class="btn btnSearch"><i class="fas fa-search"></i></button></td>
                </tr>
              </table>
            </div>
          </form>
        </div>
    </div>
    <div class="row mb-3 p-5">
        {% for vet in vets %}
        <div class="orderhead m-3 p-3">
          <table class="suggestFriends">
              <tr>
                <td rowspan="2" class="align-baseline"><img class="img-fluid vetAvatar" alt="Responsive image" src={{vet.profilePic.url}}></td>
                <td class="align-baseline" rowspan="3"><h6 class="card-title suggestStore">{{vet.user.name}}</h6></td>
                <td rowspan="2" class="align-baseline">
                  <a href="{% url 'profiles:profile-detail-view' vet.slug %}"class="btn productView" style="color:#fff !important;">
                    <i class="fa-solid fa-user-doctor suggestVet"></i>
                    View Doctor
                  </a>
                </td>
              </tr>   
          </table>
        </div>
      {% endfor %}
    </div>
    <hr>
    <div class="row mb-3">
        {% for post in posts %}
            {% if post.author.user.type == "VET" %}
                <div class="card m-3" style="width: 28rem;">
                    <div class ="card-title clearfix p-2">
                        <img class="img-fluid avatar mr-3" alt="Responsive image" src={{post.author.profilePic.url}}>
                        {{post.author.user.name}} - {{post.created|timesince}} ago
                    </div>
                        {% if post.picture %}
                            <img src="{{post.picture.url}}" class="img-vet" alt="...">
                        {% endif %}
                        {% if post.video %}
                            <video controls autoplay muted id="vid">
                                <source src={{post.video.url}} type="video/mp4"></source>
                            </video>
                        {% endif %}
                    <div class="card-body">
                        <h6 class="card-title">{{post.caption}}</h5>
                        <p class="card-tags vetTags">{{post.tags}}</p>
                    </div>
                    <div class="card-footer">
                        <a href="{% url 'profiles:profile-detail-view' post.author.slug %}" class="btn productView" style="color:#fff !important;">Sniff Profile</a>
                    </div>
                </div>
            {% endif %}  
        {% endfor %}
    </div>
</div>
            
{% endblock content %}

SmaPetz/users/templates/users/vet_search.html
{% extends 'base.html' %}
{% block title %}
Search Veterinarians
{% endblock title %}

{% block content %}
<div class="section p-5 m-3">
    <div class="row searchTerm m-3">
      <a href="{% url 'users:vet-view' %}" class="btn backStore">
        <i class="fa-solid fa-user-doctor suggestVet"></i>
        Back to the Veterinarian
      </a>
      <h3 class="pl-5"><i class="fa-solid fa-magnifying-glass"></i> "{{ query }}" </h3>
    </div>
    <div class="row searchTitle"><h3 class="m-3">Profiles: </h3><br/></div>
    <div class="row mt-4">
      {% for vet in profiles %}
        {% include 'profiles/search_list.html' %} 
      {% endfor %}
    </div>
    <hr>
    <div class="row searchTitle"><h3 class="m-3">Posts: </h3><br/></div>
    <div class="row mt-4">
      {% for post in posts %}
        {% include 'posts/post_list.html' %}
      {% endfor %}
    </div>
</div>
{% endblock content %}