SmaPetz/SmaPetz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SmaPetz/cart/urls.py
from django.urls import path
from .views import cart_detail, success

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart'),
    path('success/', success, name='success')
]

SmaPetz/products/urls.py
from django.urls import path
from .views import store_view, product, category, searchProduct

app_name = 'products'

urlpatterns = [
    path('store/', store_view, name='store-view'),
    path('search/', searchProduct, name='product-search'),
    path('<slug:category_slug>/<slug:product_slug>/', product, name='product'),
    path('<slug:category_slug>/', category, name='category'),
]

SmaPetz/profiles/urls.py
from django.urls import path
from .views import (
    profile_test_view,
    received_requests_view,
    profiles_list_view, 
    invite_profiles_list_view, 
    ProfileListView,
    ProfileDetailView, 
    send_requests, 
    remove_from_friends,
    accept_requests,
    reject_requests,
    add_products,
    display_orders
)

app_name = 'profiles'

urlpatterns = [
    # path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('profile/', profile_test_view, name='profile-test'),
    path('received-requests/', received_requests_view, name='received-requests'),
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('add_products/', add_products, name='add-products'),
    path('display_orders/', display_orders, name='display-orders'),
    
    path('<slug:slug>', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('to-request/', invite_profiles_list_view, name='request-profiles-view'),
    path('send-requests/',send_requests, name='send-request'),
    path('remove-friend/',remove_from_friends, name='remove-friend'),
    path('received-requests/accept/', accept_requests, name='accept-request'),
    path('received-requests/reject/', reject_requests, name='reject-request'),  
    
]

SmaPetz/posts/models.py
from django.db import models
from django.db import models
from profiles.models import Profile
from .validators import fileSize
from django.core.validators import FileExtensionValidator

#Post Model
class Post(models.Model):
    picture = models.ImageField(upload_to='images/', null=True , blank= True)
    video =  models.FileField(upload_to='videos/', blank= True, validators=[fileSize, FileExtensionValidator(['mp4'])])
    caption = models.TextField()
    liked_by = models.ManyToManyField(Profile, default=None, blank=True, related_name='likes')
    tags = models.CharField(max_length=100, blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE,related_name='posts')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author}-{self.caption}"
    
#to grab the number of likes
    def num_likes(self):
        return self.liked_by.all().count()

#to grab the number of comments
    def num_comments(self):
        return self.comment_set.all().count()


#to create the ordering of the posts by time
    class Meta:
        ordering = ('-created',)


#Comment Model 
class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

#Reaction Model
LIKE_CHOICES = (
    
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

SmaPetz/products/models.py
from distutils.command.upload import upload
from io import BytesIO
from pyexpat import model
from unicodedata import category
from PIL import Image
from django.core.files import File
from django.db import models
from profiles.models import Store

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    ordering = models.IntegerField(default=0)

    class Meta:
        ordering = ['ordering']

    def __str__(self):
        return self.title

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    store = models.ForeignKey(Store, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(blank=True, null=True) 
    price = models.DecimalField(max_digits=6, decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='products/', default='product.png')
    thumbnail = models.ImageField(upload_to='products/', blank =True, null=True)

    class Meta:
        ordering = ['-date_added']

    def __str__(self):
        return self.title

    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url

    def make_thumbnail(self, image, size =(300, 200)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'PNG', quality=85)
        

        thumbnail = File(thumb_io, name=image.name)

        return thumbnail
            

SmaPetz/products/forms.py
from django import forms

class AddToCartForm(forms.Form):
    quantity = forms.IntegerField()

SmaPetz/products/views.py
import imp
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
import random
from django.contrib.auth.decorators import login_required
import cart
from .models import Product, Category
from profiles.models import Store, Profile
from posts.models import Post
from cart.cart import Cart
from .forms import AddToCartForm
from django.db.models import Q

# Create your views here.
def searchProduct(request):
    query = request.GET.get('query', '')
    products = Product.objects.filter(Q(title__icontains=query) | Q(description__icontains=query))
    posts = Post.objects.filter(Q(caption__icontains=query) | Q(tags__icontains=query))
    profiles = Profile.objects.filter(Q(address__icontains=query) | Q(bio__icontains=query))
    context = { 
        'products': products,
        'query':query,
        'posts':posts,
        'profiles':profiles, 
    }
    return render(request, 'products/productSearch.html', context)


def store_view(request):
    newest_products = Product.objects.all()[0:12]
    stores = Store.objects.all()
    list_stores = list(stores)

    if len(list_stores) >= 4:
        list_stores = random.sample(list_stores, 4)
    
    context = {
        'newest_products': newest_products,
        'stores':stores
    }
    return render(request, 'products/store.html', context)

@login_required
def product(request, category_slug, product_slug):
    cart = Cart(request)
    product = get_object_or_404(Product, category__slug= category_slug, slug=product_slug)

    if request.method == 'POST':
        form = AddToCartForm(request.POST)

        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            cart.add(product_id=product.id, quantity=quantity, update_quantity=False)
            messages.success(request, 'The product was added to the cart')
            return redirect('products:product', category_slug=category_slug, product_slug=product_slug)

    else:
        form = AddToCartForm()

    similar_Products = list(product.category.products.exclude(id=product.id))

    if len(similar_Products) >= 4:
        similar_Products = random.sample(similar_Products, 4)
        
    context = {
        'product': product,
        'similar_Products':similar_Products,
        'form':form
    }
    return render(request, 'products/product.html', context)

def category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    context = {
        'category': category,
    }
    return render(request, 'products/category.html', context)

SmaPetz/products/templates/products/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Category
{% endblock title %}

{% block content %}
<div class="section pl-5">
    <div class="row justify-content-center catRow">
      <a href="{% url 'products:store-view' %}" class="btn backStore">
        <i class="fa-solid fa-store storeIcon"></i>
        Back to the Store
      </a>
      <h3>Category: {{category.title}}</h3>
    </div>
    <hr/>
    <div class="row pl-5 pr-5">
        {% for product in category.products.all %}
          {% include 'products/list_item.html' %}
        {% endfor %}
    </div>
  </div>
{% endblock content %}

SmaPetz/products/templates/products/list_item.html
<div class="card m-3 StoreProduct" style="width: 18rem;">
    <img src="{{product.get_thumbnail}}" class="card-img-top productThumb" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{product.title}}</h5>
        <p class="card-tags">${{product.price}}</p>
        
    </div>
    <div class="card-footer">
        <a href="{% url 'products:product' product.category.slug product.slug %}" class="btn productView" style="color:#fff !important;">View Product</a>
    </div>
</div>

SmaPetz/products/templates/products/product.html
{% extends 'base.html' %}
{% block title %}
Product View
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row m-3">
      <div class="col-sm-6">
        {% if product.image %}
            <figure class="figure">
                <img src="{{product.image.url}}" class="figure-img img-fluid rounded">
            </figure>
        {% endif %} 
      </div>
      <div class="col-sm-6">
        <h1 class='deatilTitle'>{{product.title}}</h1>
        <h3 class='deatilPrice mb-5'>$ {{product.price}}</h3>
        <table class="table table-borderless deatilTable m-3">
            <tbody>
              <tr>
                <th scope="row">Description: </th>
                <td>{{product.description}}</td>
              </tr>
              <tr>
                <th scope="row">Store: </th>
                <td class="badgeLink"><a href="{% url 'profiles:profile-detail-view' product.store.slug %}" class="badgeLink">{{product.store.user.name}}</a></td>
              </tr>
              <tr>
                <th scope="row">Category: </th>
                <td colspan="2" class="badgeLink"><a href="{% url 'products:category' product.category.slug %}" class="badgeLink">{{product.category}}</a></td>
              </tr>
            </tbody>
          </table>
          
          {% if messages %}
            {% for message in messages %}
              <div class="notification">{{message}}</div>
            {% endfor %}
          {% endif %}
          <form method="post" action=".">
            {% csrf_token %}
            <div class="input-group mb-3 ml-3">
              <input type="number" name="quantity" value="1" class="input form-control" min="1">
              <div class="input-group-append">
                <button class="btn addCart">Add to Cart</button>
              </div>
            </div>
          </form>  
      </div>
    </div>
    <hr>
    <div class="row similarProducts">
        <div class='col'>
            <h3 class='subtitle mb-3'>Similar Products</h3>
        </div>
    </div>
    <div class="row">
        {% if similar_Products %}
            {% for product in similar_Products %}
                {% include 'products/list_item.html' %}
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content %}

SmaPetz/products/templates/products/productSearch.html
{% extends 'base.html' %}
{% block title %}
Search Products
{% endblock title %}

{% block content %}
{% comment %} <div class="section p-5 m-3"> {% endcomment %}
    <div class="row searchTerm m-3">
      <a href="{% url 'products:store-view' %}" class="btn backStore">
        <i class="fa-solid fa-store storeIcon"></i>
        Back to the Store
      </a>
      <h3 class="pl-5"><i class="fa-solid fa-magnifying-glass"></i> "{{ query }}" </h3>
    </div>
    <div class="row searchTitle"><h3 class="m-3">Products: </h3><br/></div>
    <div class="row mt-4">
        {% for product in products %}
          {% include 'products/list_item.html' %}
        {% endfor %}
    </div>
    <hr>
    {% comment %} <div class="row searchTitle"><h3 class="m-3">Profiles: </h3><br/></div>
    <div class="row mt-4">
      {% for profile in profiles %}
        {% include 'profiles/search_list.html' %} 
      {% endfor %}
    </div>
    <hr>
    <div class="row searchTitle"><h3 class="m-3">Posts: </h3><br/></div>
    <div class="row mt-4">
      {% for post in posts %}
        {% include 'posts/post_list.html' %}
      {% endfor %}
    </div> {% endcomment %}
</div>
{% endblock content %}

SmaPetz/products/templates/products/store.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Store
{% endblock title %}

{% block content %}
<div class="section m-3">
{% comment %} <div class="container"> {% endcomment %}
    <div class="row">
      <ul class="nav ">
        {% for category in menu_categories %}
          <li class="nav-item subnav mb-2">
            <a href="{% url 'products:category' category.slug %}" class='nav-link'>{{category.title}}</a>
          <li>
        {% endfor %}
      </ul>
    </div>
    <br>
    <div class="row mb-3">
      <div class="col-2 d-flex justify-content-end imgCol">
        <img class="img-fluid justify-content-right ml-5" alt="Responsive image" src="{% static "images/product_store.png" %}">
      </div>
      <div class="col-5 d-flex align-items-start">
        <h2 class="storeHeader justify-content-left">Newest Products</h2>
      </div>
      <div class="col">
        <form method="get" action="{% url 'products:product-search' %}" class="formSearch">
          <div class="boxContainer">
            <table class="elementsContainer">
              <tr>
                <td class="align-baseline"><input type ="search" class="form-control searchInput" placeholder="Search..." name="query"></td>
                <td rowspan="2" class="align-baseline"><button class="btn btnSearch"><i class="fas fa-search"></i></button></td>
              </tr> 
            </table>
          </div>
        </form>
      </div>
    </div>
    <div class="row mb-3">
        {% for product in newest_products %}
          {% include 'products/list_item.html' %}
        {% endfor %}
    </div>
    <hr>
    <div class="row mb-3">
      <div class="col-2 d-flex justify-content-end imgCol">
        <img class="img-fluid justify-content-right ml-5" alt="Responsive image" src="{% static "images/sniff.png" %}">
      </div>
      <div class="col-5 d-flex align-items-start">
        <h2 class="storeHeader justify-content-left">Sniff Stores</h2>
      </div>
    <div>
    <br>
    <div class="row mb-3 sugFriendDiv">
      {% for store in stores %}
        <div class="orderhead m-3 p-3">
          <table class="suggestFriends">
              <tr>
                <td rowspan="2" class="align-baseline"><img class="img-fluid storeAvatar" alt="Responsive image" src={{store.profilePic.url}}></td>
                <td class="align-baseline" rowspan="3"><h6 class="card-title suggestStore">{{store.user.name}}</h6></td>
                <td rowspan="2" class="align-baseline">
                  <a href="{% url 'profiles:profile-detail-view' store.slug %}"class="btn productView" style="color:#fff !important;">
                    <i class="fa-solid fa-store storeIcon"></i>
                    View Store
                  </a>
                </td>
              </tr>   
          </table>
        </div>
      {% endfor %}
    </div>
</div>
{% endblock content %}