SmaPetz/SmaPetz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('users/', include('users.urls', namespace='users')),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

SmaPetz/cart/urls.py
from django.urls import path
from .views import cart_detail, success

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart'),
    path('success/', success, name='success')
]

SmaPetz/posts/urls.py
from django.urls import path
from .views import home_view, PostDeleteView, PostUpdateView, like_unlike_post

app_name = 'posts'

urlpatterns = [
    path('', home_view, name='home-view'),
    path('liked/',like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

SmaPetz/products/urls.py
from django.urls import path
from .views import store_view, product, category, searchProduct

app_name = 'products'

urlpatterns = [
    path('store/', store_view, name='store-view'),
    path('search/', searchProduct, name='product-search'),
    path('<slug:category_slug>/<slug:product_slug>/', product, name='product'),
    path('<slug:category_slug>/', category, name='category'),
]

SmaPetz/profiles/urls.py
from django.urls import path
from .views import (
    profile_test_view,
    received_requests_view,
    profiles_list_view, 
    invite_profiles_list_view, 
    ProfileListView,
    ProfileDetailView, 
    send_requests, 
    remove_from_friends,
    accept_requests,
    reject_requests,
    add_products,
    display_orders
)

app_name = 'profiles'

urlpatterns = [
    # path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('profile/', profile_test_view, name='profile-test'),
    path('received-requests/', received_requests_view, name='received-requests'),
    path('all-profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('add_products/', add_products, name='add-products'),
    path('display_orders/', display_orders, name='display-orders'),
    
    path('<slug:slug>', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('to-request/', invite_profiles_list_view, name='request-profiles-view'),
    path('send-requests/',send_requests, name='send-request'),
    path('remove-friend/',remove_from_friends, name='remove-friend'),
    path('received-requests/accept/', accept_requests, name='accept-request'),
    path('received-requests/reject/', reject_requests, name='reject-request'),  
    
]

SmaPetz/users/urls.py
from django.urls import path, re_path, reverse_lazy
from .views import register, login_view, logout_view, home_view, about_view,vet_view, searchVet
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

app_name = 'users'

urlpatterns = [
    path('', home_view, name='dashboard'),
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('about/', about_view, name='about-view'),    
    path('vet/', vet_view, name='vet-view'), 
    path('vetSearch/', searchVet, name='search-vet'),
]

SmaPetz/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- cropper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.css">

    <!-- custom css & js-->
    <link rel="stylesheet" type="text/css" href={% static 'style.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'profiles/profile.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'posts/post.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'users/users.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'products/product.css' %}>
    <link rel="stylesheet" type="text/css" href={% static 'cart/cart.css' %}>
    
    <script src={% static 'main.js' %} defer></script>
    <script src={% static 'profiles/profile.js' %} defer></script>
    <script src={% static 'posts/post.js' %} defer></script>
    <script src={% static 'cart/cart.js' %} defer></script>
    {% block extrahead %}{% endblock %}


    <!-- font awesome css-->
    <script src="https://kit.fontawesome.com/27743883ae.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&family=Roboto+Slab:wght@300&display=swap" rel="stylesheet">
    {% block scripts %}{% endblock scripts %}

    <title>Pet Network | {% block title %}{% endblock title %}</title>
  </head>

  <body>
    <!--Navbar-->
    {% include 'navbar.html' %}
      <div class="container-fluid conBase pt-3">
          {% block content %}
          {% endblock content %}
      </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

SmaPetz/templates/navbar.html
{% load static %}

{% url 'posts:home-view' as path_to_posts %}
{% url 'profiles:profile-test' as path_to_profile %}
{% url 'users:about-view' as path_to_about %}
{% url 'users:vet-view' as path_to_vet %}
{% url 'profiles:all-profiles-view' as path_to_allProfiles %}
{% url 'profiles:received-requests' as path_to_requests %}
{% url 'profiles:request-profiles-view' as path_to_sendRequests %}
{% url 'products:store-view' as path_to_stores %}
{% url 'cart:cart' as path_to_cart %}

<div class="grad-bar"></div>

<nav class="navbar navbar-expand-lg navbar-light navbar-mainbg">
  <a class="navbar-brand" href="#">
    {% if request.user.is_authenticated %}
      <img class="nav_logo" src="{% static "images/bg.png" %}" style ="height: 90px; width: 130px" /> 
    {% endif %}
    SmaPetz
  </a>
  <button class="navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fa-solid fa-bars"></i>
  </button>

  <div class="collapse navbar-collapse pr-3" id="navbarSupportedContent" >
    <ul class="navbar-nav ml-auto">
      <li class="{% if request.path == path_to_about %}active{% endif %} nav-item">
        <a class="nav-link" href="{{path_to_about}}">About </a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="{% if request.path == path_to_posts %}active{% endif %} nav-item">
          <a class="nav-link" href="{{path_to_posts}}">Feed</a>
      </li>
      <li class="{% if request.path == path_to_sendRequests or request.path == path_to_requests or request.path == path_to_allProfiles %}active{% endif %}nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Friends
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{path_to_sendRequests}}">Sent Requests</a>
          <a class="dropdown-item" href="{{path_to_requests}}">
            Received Requests &nbsp; <label class ="requests_no">{{requests_no}}</label>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{{path_to_allProfiles}}">All Profiles</a>
        </div>
      </li>
      <li class="{% if request.path == path_to_profile %}active{% endif %} nav-item">
          <a class="nav-link" href="{{path_to_profile}}">
            <img class="img-fluid profile-pic" src={{picture.url}} style="width: 22px; height:22px; border-radius: 50px;" /> &nbsp;
            {{request.user.name}}
          </a>
      </li>
      {% endif %}
      <li class="{% if request.path == path_to_stores %}active{% endif %} nav-item">
          <a class="nav-link" href="{{path_to_stores}}">Store</a>
      </li>
      <li class="{% if request.path == path_to_vet %}active{% endif %} nav-item">
          <a class="nav-link" href="{{path_to_vet}}">Veterinarian</a>
      </li>
      
      <li class="{% if request.path == path_to_cart %}active{% endif %} nav-item">
        <a class="nav-link" href="{{path_to_cart}}"><i class="fa-solid fa-cart-arrow-down"></i>{% if cart %}({{cart|length}}){% endif %}</a>
      </li>
        
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:logout' %}"><i class="fa-solid fa-power-off" id="log-out"></i></i></a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
      </li>
      {% endif %}

    </ul>
  </div>
</nav>